foreground #a3bcc0
background #040505

selection_background #3BA4BE
selection_foreground #040505

cursor #a3bcc0
cursor_text_color #040505

url_color #3BA4BE

# black
color0   #040505
color8   #728386

# red / critical
color1   #864DB1
color9   #9D63CB

# green
color2   #9EB069
color10  #B3C47B

# yellow / highlight
color3   #5C59A5
color11  #7470BF

# blue
color4   #2E6599
color12  #3B7BB5

# magenta
color5   #4934B3
color13  #6250C9

# cyan
color6   #3BA4BE
color14  #56BDD4

# white
color7   #a3bcc0
color15  #d5e1e3