foreground #cacfc4
background #13131a

selection_background #538E8E
selection_foreground #13131a

cursor #cacfc4
cursor_text_color #13131a

url_color #7DA193

# black
color0   #13131a
color8   #5d615f

# red
color1   #DC8678
color9   #E69A8E

# green
color2   #538E8E
color10  #6FA6A0

# yellow
color3   #B8A06F
color11  #CBB784

# blue
color4   #6F91A8
color12  #88ABC1

# magenta
color5   #9A83A3
color13  #B39AB9

# cyan
color6   #6FA8A3
color14  #89C0B9

# white
color7   #cacfc4
color15  #F0F2EC