######################
### SOURCING FILES ###
######################

source = ~/.config/hypr/modules/lagacy/monitors.conf
source = ~/.config/hypr/modules/lagacy/autostart.conf
source = ~/.config/hypr/modules/lagacy/programs.conf
source = ~/.config/hypr/modules/lagacy/binds.conf
source = ~/.config/hypr/modules/lagacy/env.conf
source = ~/.config/hypr/modules/lagacy/input.conf
source = ~/.config/hypr/modules/lagacy/decorations.conf
source = ~/.config/hypr/modules/lagacy/animations.conf
source = ~/.config/hypr/modules/lagacy/windowrules.conf
source = ~/.config/hypr/modules/lagacy/layout.conf
source = ~/.config/hypr/modules/lagacy/misc.conf