################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, 1366x768@59.99, auto,1 
monitor = HDMI-A-1, 1366x768@75, auto, 1

################
### WORKSPACES ###
################

workspace = 1, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 2, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
