font_family CaskaydiaCove Nerd Font Mono
font_size   14

disable_ligatures no
enable_audio_bell no

shell 		  zsh
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size  no
initial_window_width  640
initial_window_height 480
window_padding_width  17
cursor_blink_interval 0

background_opacity 	 0.80
scrollbar_handle_opacity 0
scrollbar_track_opacity  0
scrollbar_hover_opacity  0
confirm_os_window_close  0

sync_to_monitor no

# Colors

background #1e1f28
foreground #f8f8f2
cursor #bbbbbb
selection_background #44475a
color0 #000000
color8 #545454
color1 #ff5555
color9 #ff5454
color2 #50fa7b
color10 #50fa7b
color3 #f0fa8b
color11 #f0fa8b
color4 #bd92f8
color12 #bd92f8
color5 #ff78c5
color13 #ff78c5
color6 #8ae9fc
color14 #8ae9fc
color7 #bbbbbb
color15 #ffffff
selection_foreground #1e1f28
