foreground            #d7f1ff
background            #0d1117
selection_foreground  #0d1117
selection_background  #77e4ff
cursor                #77e4ff
cursor_text_color     #0d1117
active_tab_foreground #0d1117
active_tab_background #77e4ff
inactive_tab_foreground #8ea7b5
inactive_tab_background #151d27

color0  #111821
color1  #ff8f98
color2  #8fe3b0
color3  #f0c674
color4  #63b3ff
color5  #9b8cff
color6  #77e4ff
color7  #d7f1ff
color8  #51606f
color9  #ffb3b9
color10 #baf2cc
color11 #f6db95
color12 #8bc5ff
color13 #b8aaff
color14 #a0efff
color15 #effbff
