background  #0a0b0d
foreground  #f5f1de

cursor      #cdccbe

selection_foreground #0a0b0d
selection_background #cdccc0

color0  #1a1d24
color8  #687985
color1  #8e5157
color9  #aa7077
color2  #89b88f
color10 #92c399
color3  #baab81
color11 #afa07b
color4  #93acc6
color12 #87a1b6
color5  #b49dae
color13 #ceafc4
color6  #86b79e
color14 #addec5
color7  #cac2a2
color15 #dfd6ac
