background  #0a0b0d
foreground  #f5f1de

cursor      #cdccbe

selection_foreground #0a0b0d
selection_background #cdccc0

# color0  #1a1d24
# color8  #687985
# color1  #8e5157
# color9  #aa7077
# color2  #89b88f
# color10 #92c399
# color3  #baab81
# color11 #afa07b
# color4  #93acc6
# color12 #87a1b6
# color5  #b49dae
# color13 #ceafc4
# color6  #86b79e
# color14 #addec5
# color7  #cac2a2
# color15 #dfd6ac

# black
color0   #0f0f10
color8   #5a6065

# red
color1   #cb6f7d
color9   #dd8190

# green
color2   #76b49b
color10  #8bc7af

# yellow
color3   #d0ab62
color11  #e4bf77

# blue
color4   #6894b3
color12  #80abc9

# magenta
color5   #a27ac2
color13  #b78fd8

# cyan
color6   #5ca8bf
color14  #74bfd6

# white
color7   #bec8ca
color15  #f2f6f7